name: issue forms example_2
description: "Example of GitHub's new feature: issue forms"
title: "タイトル: "

body:
  - type: markdown
    attributes:
      value: |
        `type: markdown` はフォームに表示されるがsubmitされない(登録されたissueには記載されない)。
        issue 登録者向けのメッセージとして使えそう。
  - type: input
    id: input-1
    attributes:
      label: Input
      description: "type: input"
      placeholder: placeholder も書ける
    validations:
      required: false
  - type: dropdown
    id: dropdown-1
    attributes:
      label: Dropdown
      description: |
        type: dropdown
        multiple: true で複数選択可能に
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - IE11
      multiple: true
    validations:
      required: true
  - type: checkboxes
    id: checkboxes-1
    attributes:
      label: Checkboxes
      description: "type: checkboxes"
      options:
        - label: Foo
        - label: Bar (This is required)
          required: true
        - label: Baz
  - type: textarea
    id: textarea-1
    attributes:
      label: Textarea
      description: Textarea
      value: "value で初期値を指定できる"
    validations:
      required: true
  - type: textarea
    id: textarea-2
    attributes:
      label: "Textarea (render: javascript)"
      description: "render: <言語> を指定するとコードブロックになり、指定した言語でシンタックスハイライトができる"
      render: javascript
